DATASET:
  PART_COUNT: 1
  SIZE: 3610
  PATH: ./data/datasets/COVID/tfrecords/COVID-r%02d.tfrecords.%03d
  PATH_TEST: ./data/datasets/COVID/tfrecords/COVID_test-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 8
  FLIP_IMAGES: False
MODEL:
  LATENT_SPACE_SIZE: 32
  LAYER_COUNT: 7
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  CHANNELS: 1
OUTPUT_DIR: covid_results
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 10
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 60
  LOD_2_BATCH_1GPU: [128, 128, 128,   64]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015]
